//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/AppRestFastFoodService.Model")]
    public partial class Cliente : object
    {
        
        private string ApellidosField;
        
        private string ContraseniaField;
        
        private string DireccionField;
        
        private string EmailField;
        
        private System.Nullable<System.DateTime> FechaCreacionField;
        
        private System.Nullable<System.DateTime> FechaModifacionField;
        
        private System.Nullable<System.DateTime> FechaNacField;
        
        private int IdClienteField;
        
        private string IdDepartamentoField;
        
        private string IdDistritoField;
        
        private string IdProvinciaField;
        
        private string IndAutorizaDatoField;
        
        private string NombresField;
        
        private string NumerocelularField;
        
        private string TipoDocIdField;
        
        private string UsuarioCreacionField;
        
        private string UsuarioModificacionField;
        
        private string numerodocField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos
        {
            get
            {
                return this.ApellidosField;
            }
            set
            {
                this.ApellidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia
        {
            get
            {
                return this.ContraseniaField;
            }
            set
            {
                this.ContraseniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaCreacion
        {
            get
            {
                return this.FechaCreacionField;
            }
            set
            {
                this.FechaCreacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModifacion
        {
            get
            {
                return this.FechaModifacionField;
            }
            set
            {
                this.FechaModifacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaNac
        {
            get
            {
                return this.FechaNacField;
            }
            set
            {
                this.FechaNacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente
        {
            get
            {
                return this.IdClienteField;
            }
            set
            {
                this.IdClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDepartamento
        {
            get
            {
                return this.IdDepartamentoField;
            }
            set
            {
                this.IdDepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDistrito
        {
            get
            {
                return this.IdDistritoField;
            }
            set
            {
                this.IdDistritoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProvincia
        {
            get
            {
                return this.IdProvinciaField;
            }
            set
            {
                this.IdProvinciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndAutorizaDato
        {
            get
            {
                return this.IndAutorizaDatoField;
            }
            set
            {
                this.IndAutorizaDatoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numerocelular
        {
            get
            {
                return this.NumerocelularField;
            }
            set
            {
                this.NumerocelularField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocId
        {
            get
            {
                return this.TipoDocIdField;
            }
            set
            {
                this.TipoDocIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioCreacion
        {
            get
            {
                return this.UsuarioCreacionField;
            }
            set
            {
                this.UsuarioCreacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioModificacion
        {
            get
            {
                return this.UsuarioModificacionField;
            }
            set
            {
                this.UsuarioModificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numerodoc
        {
            get
            {
                return this.numerodocField;
            }
            set
            {
                this.numerodocField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RestServiceReference.IFastFoodServiceApi")]
    public interface IFastFoodServiceApi
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodServiceApi/saludo", ReplyAction="http://tempuri.org/IFastFoodServiceApi/saludoResponse")]
        System.Threading.Tasks.Task<string> saludoAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodServiceApi/cliente", ReplyAction="http://tempuri.org/IFastFoodServiceApi/clienteResponse")]
        System.Threading.Tasks.Task<RestServiceReference.Cliente> clienteAsync(RestServiceReference.Cliente pClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastFoodServiceApi/clientes", ReplyAction="http://tempuri.org/IFastFoodServiceApi/clientesResponse")]
        System.Threading.Tasks.Task<RestServiceReference.Cliente[]> clientesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IFastFoodServiceApiChannel : RestServiceReference.IFastFoodServiceApi, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class FastFoodServiceApiClient : System.ServiceModel.ClientBase<RestServiceReference.IFastFoodServiceApi>, RestServiceReference.IFastFoodServiceApi
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FastFoodServiceApiClient() : 
                base(FastFoodServiceApiClient.GetDefaultBinding(), FastFoodServiceApiClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IFastFoodServiceApi.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FastFoodServiceApiClient(EndpointConfiguration endpointConfiguration) : 
                base(FastFoodServiceApiClient.GetBindingForEndpoint(endpointConfiguration), FastFoodServiceApiClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FastFoodServiceApiClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FastFoodServiceApiClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FastFoodServiceApiClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FastFoodServiceApiClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FastFoodServiceApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> saludoAsync(string nombre)
        {
            return base.Channel.saludoAsync(nombre);
        }
        
        public System.Threading.Tasks.Task<RestServiceReference.Cliente> clienteAsync(RestServiceReference.Cliente pClient)
        {
            return base.Channel.clienteAsync(pClient);
        }
        
        public System.Threading.Tasks.Task<RestServiceReference.Cliente[]> clientesAsync()
        {
            return base.Channel.clientesAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFastFoodServiceApi))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFastFoodServiceApi))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:60394/FastFoodServiceApi.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FastFoodServiceApiClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IFastFoodServiceApi);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FastFoodServiceApiClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IFastFoodServiceApi);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IFastFoodServiceApi,
        }
    }
}
