//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRestFastFoodService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int IdCliente { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string TipoDocId { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public string Numerocelular { get; set; }
        public string Email { get; set; }
        public string Contrasenia { get; set; }
        public string IdDepartamento { get; set; }
        public string IdProvincia { get; set; }
        public string IdDistrito { get; set; }
        public string Direccion { get; set; }
        public string IndAutorizaDato { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModifacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string numerodoc { get; set; }
    }
}
